// GET ONE PRODUCT BY ID (PARAMETER)
GET http://localhost:5000/product/6393fb7141afa7ad94401136
###

// GET ALL PRODUCTS
GET http://localhost:5000/product

###

// CREATE A PRODUCT
POST http://localhost:5000/product/
Content-Type: application/json

{
    "title": "alimento x500gr pedigree",
    "price": 100,
    "description": "comida para perros",
    "stock": 25,
    "category": "alimento"
}

###

// UPDATE A PRODUCT
PUT http://localhost:5000/product/6393f3f869e0132fa43f828e
Content-Type: application/json

{
    "title": "alimento x500gr pedigree",
    "price": 150,
    "description": "comida para perros",
    "stock": 35,
    "category": "alimentos",
    "subcategory": "perro"
}

###

// DELETE A PRODUCT BY ID (PARAMETER)
DELETE http://localhost:5000/product/6393f89d1ee8c9cbf4c40020

###

// DELETE ALL PRODUCTS
DELETE http://localhost:5000/product/