GET http://localhost:5000/user/15
###
GET http://localhost:5000/user/
###
POST http://localhost:5000/user
###
PUT http://localhost:5000/user/4

// LOGIN
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "florOjeda@gmail.com",
    "password": "jongin88"
}

// REGISTER
###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "firstName": "Florencia",
    "lastName": "Ojeda",
    "email": "florOjeda@gmail.com",
    "password": "jongin88",
    "password2": "jongin88"
}

// LOG OUT
###
DELETE   http://localhost:5000/user/logout